[{"name": "test_greeter.GreeterTest.test_greets", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_greeter.py\", line 15, in test_greets\n    g = Greeter()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.0"], "status": "failed", "message": "src.greeter.Greeter does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_can_add_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 51, in test_can_add_multiple\n    l = Lastiruuma(5)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_can_add_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 38, in test_can_add_single\n    l = Lastiruuma(2)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_can_init", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 15, in test_can_init\n    self.assertTrue(Lastiruuma(2),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_can_not_add_too_heavy", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 67, in test_can_not_add_too_heavy\n    l = Lastiruuma(1)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_has_maksimipaino", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 20, in test_has_maksimipaino\n    Lastiruuma(1)._Lastiruuma__maksimipaino,\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_has_matkalaukut", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 29, in test_has_matkalaukut\n    self.assertTrue(hasattr(Lastiruuma(2), '_Lastiruuma__matkalaukut'),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_str_empty", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 154, in test_str_empty\n    Lastiruuma(1).__str__(),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_str_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 158, in test_str_single\n    m1 = Matkalaukku(5)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_tavarat_empty_at_start", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 34, in test_tavarat_empty_at_start\n    len(Lastiruuma(1)._Lastiruuma__matkalaukut),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_tulosta_tavarat_empty", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 125, in test_tulosta_tavarat_empty\n    Lastiruuma(1).tulosta_tavarat()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_tulosta_tavarat_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 131, in test_tulosta_tavarat_multiple\n    m = Matkalaukku(10)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_yhteispaino_failed_add", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 114, in test_yhteispaino_failed_add\n    m = Matkalaukku(15)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_yhteispaino_init", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 82, in test_yhteispaino_init\n    Lastiruuma(1).yhteispaino(),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_yhteispaino_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 96, in test_yhteispaino_multiple\n    l = Lastiruuma(21)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_lastiruuma.LastiruumaTest.test_yhteispaino_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_lastiruuma.py\", line 86, in test_yhteispaino_single\n    l = Lastiruuma(15)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.3"], "status": "failed", "message": "src.lastiruuma.Lastiruuma does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_can_add_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 50, in test_can_add_multiple\n    m = Matkalaukku(5)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_can_add_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 37, in test_can_add_single\n    m = Matkalaukku(2)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_can_init", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 14, in test_can_init\n    self.assertTrue(Matkalaukku(2),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_can_not_add_too_heavy", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 66, in test_can_not_add_too_heavy\n    m = Matkalaukku(1)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_has_maksimipaino", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 19, in test_has_maksimipaino\n    Matkalaukku(1)._Matkalaukku__maksimipaino,\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_has_tavarat", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 28, in test_has_tavarat\n    self.assertTrue(hasattr(Matkalaukku(2), '_Matkalaukku__tavarat'),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_raskain_tavara_empty", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 109, in test_raskain_tavara_empty\n    self.assertIsNone(Matkalaukku(1).raskain_tavara(),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_raskain_tavara_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 122, in test_raskain_tavara_multiple\n    m = Matkalaukku(10)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_raskain_tavara_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 113, in test_raskain_tavara_single\n    t = Tavara(\"kivi\", 1)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.tavara.Tavara does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_str_empty", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 152, in test_str_empty\n    Matkalaukku(0).__str__(),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_str_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 164, in test_str_multiple\n    m = Matkalaukku(5)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_str_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 156, in test_str_single\n    m = Matkalaukku(1)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_tavarat_empty_at_start", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 33, in test_tavarat_empty_at_start\n    len(Matkalaukku(1)._Matkalaukku__tavarat),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_tulosta_tavarat_empty", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 133, in test_tulosta_tavarat_empty\n    Matkalaukku(1).tulosta_tavarat()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_tulosta_tavarat_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 139, in test_tulosta_tavarat_multiple\n    m = Matkalaukku(10)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_yhteispaino_failed_add", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 101, in test_yhteispaino_failed_add\n    m = Matkalaukku(1)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_yhteispaino_init", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 79, in test_yhteispaino_init\n    Matkalaukku(1).yhteispaino(),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_yhteispaino_multiple", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 91, in test_yhteispaino_multiple\n    m = Matkalaukku(15)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_matkalaukku.MatkalaukkuTest.test_yhteispaino_single", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_matkalaukku.py\", line 83, in test_yhteispaino_single\n    m = Matkalaukku(15)\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.2"], "status": "failed", "message": "src.matkalaukku.Matkalaukku does not exist!"}, {"name": "test_tavara.TavaraTest.test_can_init", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_tavara.py\", line 13, in test_can_init\n    self.assertTrue(Tavara(\"a\", 1),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.1"], "status": "failed", "message": "src.tavara.Tavara does not exist!"}, {"name": "test_tavara.TavaraTest.test_correct_str", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_tavara.py\", line 34, in test_correct_str\n    Tavara(\"Kivi\", 1).__str__(),\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.1"], "status": "failed", "message": "src.tavara.Tavara does not exist!"}, {"name": "test_tavara.TavaraTest.test_has_name", "backtrace": ["  File \"/usr/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/test_tavara.py\", line 26, in test_has_name\n    Tavara(\"Kivi\", 1).paino,\n", "  File \"/home/henrik/Code/tmc-python3-utils/test/resources/complex/test/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"], "passed": false, "points": ["1.1"], "status": "failed", "message": "src.tavara.Tavara does not exist!"}]